# CI service discovery configuration
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false

# CI security configuration
security:
  access-token-secret: dummy-secret-key
  cluster-keys:
    AUTH: dummy-auth-key
    USERS: dummy-users-key
    MEDIA: dummy-media-key
    DISCOVERY: dummy-discovery-key
    STREAMING: dummy-streaming-key
    BILLING: dummy-billing-key

# CI observability configuration
management:
  tracing:
    export:
      enabled: false
  otlp:
    metrics:
      export:
        enabled: false